export enum ExceptionCode {
  NOT_FOUND = 'not_found',
  UNAUTHORIZED = 'unauthorized',
  FORBIDDEN = 'forbidden',
  BAD_REQUEST = 'bad_request',
  CONFLICT = 'conflict',
  UNKNOWN = 'unknown',
  HTTP_EXCEPTION = 'http_exception',
  UNPROCESSABLE_ENTITY = 'unprocessable_entity',
  VALIDATION_FAILED = 'validation_failed',
  INVALID_ARGUMENT = 'invalid_argument',
  INVALID_ACCESS_TOKEN_TYPE = 'invalid_access_token_type',
  INVALID_ACCESS_TOKEN = 'invalid_access_token',
  MISSING_ACCESS_TOKEN = 'missing_access_token',
}
